name: Run Inference Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  inference-tests:
    runs-on: ubuntu-latest
    env:
      # Local Broker
      TEST_MQTT_BROKER_HOST: localhost
      TEST_MQTT_BROKER_PORT: "1883"
    services:
      mqtt:
        image: emqx/emqx:5.10.4
        ports:
          - 1883:1883
        options: >-
          --health-cmd "emqx ctl status"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20
          --health-start-period 10s
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          # cache: 'pip' # Caching didn't make the CI faster and cache is quite big (4GB)

      - name: Install inference dependencies
        working-directory: ./inference
        run: |
          pip install -r requirements.txt -r requirements-dev.txt --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Run static inference checks
        working-directory: ./inference
        run: python -m compileall app tests

      - name: Run inference tests
        working-directory: ./inference
        run: pytest tests -s
