name: Run Core Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  core-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.6
        with:
          environments: test-cpu
          frozen: true

      - name: Run tests on CPU
        run: pixi run -e test-cpu test

  core-tests-pip:
    name: core-tests (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up MSVC (for torch.compile on windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install tirex-2 from source
        run: pip install ".[gluonts,fev]" pytest

      - name: Run tests on CPU
        run: pytest test/
